### ISSUE TITLE
Scala 2.12 compatibility

### ISSUE THREAD

**Issue by zifeo** [typesafehub/lightbend-emoji#2]
Is this library published for 2.12?

**Comment by SethTisue** [comment]
four whole hours and no reply yet. are maintainers AWOL? 😡

**Comment by scotdalton** [comment]
Any update on this? Looks like support for 2.12 has been added but not published.

**Comment by gurghet** [comment]
+1

**Comment by wsargent** [comment]
@SethTisue I can add you as a maintainer if you like...

**Comment by SethTisue** [comment]
depends. is this covered by Lightbend support subscrtiptions? I don't want my beeper going off at the club every time there's a late night emoji emergency at GiantBank MegaCorp

**Comment by SethTisue** [comment]
as a gesture of goodwill, I have added typesafe-emoji to the Scala community build in https://github.com/scala/community-builds/pull/496

**Comment by wsargent** [comment]
you're too kind

**Comment by SethTisue** [comment]
> I can add you as a maintainer if you like...

@wsargent I'm ready to wear that big, heavy, shiny crown. king me

**Comment by SethTisue** [comment]
<img src="https://s-media-cache-ak0.pinimg.com/564x/e9/00/ec/e900ec03e696333146f2c37f0a1be239.jpg">

**Comment by scotdalton** [comment]
any update on this?

**Comment by SethTisue** [comment]
I have been too busy drawing UML diagrams and trying to make the office foosball table level to devote my full attention to this. See #4 for an increment on work on this. Once @wsargent runs it by our legal team, we should be ready to publish.

**Comment by wsargent** [comment]
approved, modulo questions about the name.  Do you think anyone will take "likebend" seriously?

**Comment by SethTisue** [comment]
I'll focus-group it next week

**Comment by SethTisue** [comment]
1.1.0 is published under the com.typesafe organization. 1.1.1 to follow under com.lightbend; tracking that at #6
